version: "3.7"

services:

  
  
  chat:
    image: node:16.13.1-alpine3.13
    command: sh -c "yarn install && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && yarn run dev "
    ports:
      - 3004:3004
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      
      PORT: 3004
     
    


volumes:
  todo-mysql-data: